version: '3.9'

services:
  backend:
    build:
      context: ./backend   # <-- Look for Dockerfile in backend/
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: userpassword
      DB_NAME: mydatabase
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
